#!/bin/bash
set -eu

IWYU_VERSION_STR=$(docker run --rm ${IMAGE_NAME} --version)
IWYU_VERSION=$(echo ${IWYU_VERSION_STR} | sed "s/.*include-what-you-use\s*\([0-9]*\.[0-9]*\).*/\1/")
CLANG_VERSION=$(echo ${IWYU_VERSION_STR} | sed "s/.*based on .* clang version\s*\([0-9]*\.[0-9]*.[0-9]*\).*/\1/")
CLANG_MAJOR=${CLANG_VERSION%%.*}

function tag () {
    docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:$1"
    docker push "${DOCKER_REPO}:$1"
}

tag "${DOCKER_TAG}-clang-${CLANG_MAJOR}"
tag "${DOCKER_TAG}-iwyu-${IWYU_VERSION}"
tag "${DOCKER_TAG}-iwyu-${IWYU_VERSION}-clang-${CLANG_MAJOR}"

if [ "${DOCKER_TAG}" = "latest" ]; then
    tag "clang-${CLANG_MAJOR}"
    tag "iwyu-${IWYU_VERSION}-clang-${CLANG_MAJOR}"
fi
