#!/bin/bash
set -eu

IWYU_VERSION_STR=$(docker run --rm ${IMAGE_NAME} --version)
IWYU_VERSION=$(echo ${IWYU_VERSION_STR} | sed "s/.*include-what-you-use\s*\([0-9]*\.[0-9]*\).*/\1/")
CLANG_VERSION=$(echo ${IWYU_VERSION_STR} | sed "s/.*based on .*clang version\s*\([0-9]*\.[0-9]*.[0-9]*\).*/\1/")
CLANG_MAJOR="${CLANG_VERSION%%.*}"
CLANG_MINOR="${CLANG_VERSION%.*.*}"

CLANG_TAG="${CLANG_MAJOR}"
if [ "${CLANG_MAJOR}" -le 3 ]; then
    CLANG_TAG="${CLANG_MAJOR}.${CLANG_MINOR}"
fi

function tag () {
    docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:$1"
    docker push "${DOCKER_REPO}:$1"
}

tag "${DOCKER_TAG}-clang-${CLANG_TAG}"
tag "${DOCKER_TAG}-iwyu-${IWYU_VERSION}"
tag "${DOCKER_TAG}-iwyu-${IWYU_VERSION}-clang-${CLANG_TAG}"

if [ "${DOCKER_TAG}" = "latest" ]; then
    tag "clang-${CLANG_TAG}"
    tag "iwyu-${IWYU_VERSION}-clang-${CLANG_TAG}"
fi
