name: Docker Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        default: 'latest'
        description: 'ubuntu docker tag'
        required: true
      clang_version:
        default: '13'
        description: 'clang version. see https://apt.llvm.org/'
        required: true
      iwyu_baranch:
        default: 'clang_13'
        description: 'include-what-you-use branch. see https://github.com/include-what-you-use/include-what-you-use/branches'
        required: true

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set Default build-args
        id: default-build-args
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh workflow view "${GITHUB_WORKFLOW}" --yaml | tee workflow.yml
          echo "##[set-output name=ubuntu_version;]$(yq '.on.workflow_dispatch.inputs.ubuntu_version.default' workflow.yml)"
          echo "##[set-output name=clang_version;]$(yq '.on.workflow_dispatch.inputs.clang_version.default' workflow.yml)"
          echo "##[set-output name=iwyu_baranch;]$(yq '.on.workflow_dispatch.inputs.iwyu_baranch.default' workflow.yml)"
      - name: Set build-args
        id: build-args
        run: |
          echo "::echo::on"
          echo "##[set-output name=ubuntu_version;]${{ github.event.inputs.ubuntu_version || steps.default-build-args.outputs.ubuntu_version }}"
          echo "##[set-output name=clang_version;]${{ github.event.inputs.clang_version || steps.default-build-args.outputs.clang_version }}"
          echo "##[set-output name=iwyu_baranch;]${{ github.event.inputs.iwyu_baranch || steps.default-build-args.outputs.iwyu_baranch }}"
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: srzzumix/iwyu:${{ steps.build-args.outputs.ubuntu_version }}
          build-args: |
            UBUNTU_VERSION=${{ steps.build-args.outputs.ubuntu_version }}
            CLANG_VERSION=${{ steps.build-args.outputs.clang_version }}
            IWYU_BRANCH=${{ steps.build-args.outputs.iwyu_baranch }}
        if: (github.event_name != 'push' || github.ref != 'refs/heads/master')
      - name: Push to latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: srzzumix/iwyu:${{ steps.build-args.outputs.ubuntu_version }}
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master')
      - name: Push to version tag
        env:
          DOCKER_TAG: ${{ steps.build-args.outputs.ubuntu_version }}
          IMAGE_NAME: srzzumix/iwyu:${{ steps.build-args.outputs.ubuntu_version }}
          DOCKER_REPO: srzzumix/iwyu
        run: |
          ./hooks/post_push
