name: Docker Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        default: 'latest'
        description: 'ubuntu docker tag'
        required: true
      clang_version:
        default: '15'
        description: 'clang version. see https://apt.llvm.org/'
        required: true
      iwyu_baranch:
        default: 'clang_15'
        description: 'include-what-you-use branch. see https://github.com/include-what-you-use/include-what-you-use/branches'
        required: true

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: SetUp buildx
        uses: docker/setup-buildx-action@v2
      - name: Set Default build-args
        id: default-build-args
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh workflow view "${GITHUB_WORKFLOW}" --yaml | tee workflow.yml
          echo "ubuntu_version=$(yq '.on.workflow_dispatch.inputs.ubuntu_version.default' workflow.yml)" >> "${GITHUB_OUTPUT}"
          echo "clang_version=$(yq '.on.workflow_dispatch.inputs.clang_version.default' workflow.yml)" >> "${GITHUB_OUTPUT}"
          echo "iwyu_baranch=$(yq '.on.workflow_dispatch.inputs.iwyu_baranch.default' workflow.yml)" >> "${GITHUB_OUTPUT}"
      - name: Set build-args
        id: build-args
        run: |
          echo "::echo::on"
          echo "ubuntu_version=${{ github.event.inputs.ubuntu_version || steps.default-build-args.outputs.ubuntu_version }}" >> "${GITHUB_OUTPUT}"
          echo "clang_version=${{ github.event.inputs.clang_version || steps.default-build-args.outputs.clang_version }}" >> "${GITHUB_OUTPUT}"
          echo "iwyu_baranch=${{ github.event.inputs.iwyu_baranch || steps.default-build-args.outputs.iwyu_baranch }}" >> "${GITHUB_OUTPUT}"
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          tags: |
            srzzumix/iwyu:local
          build-args: |
            UBUNTU_VERSION=${{ steps.build-args.outputs.ubuntu_version }}
            CLANG_VERSION=${{ steps.build-args.outputs.clang_version }}
            IWYU_BRANCH=${{ steps.build-args.outputs.iwyu_baranch }}
      - name: List version tags
        env:
          DOCKER_TAG: ${{ steps.build-args.outputs.ubuntu_version }}
          IMAGE_NAME: srzzumix/iwyu:local
          DOCKER_REPO: srzzumix/iwyu
        run: |
          ./hooks/tags > tags.txt
      - name: Add latest tags
        run: |
          echo srzzumix/iwyu:latest >> tags.txt
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master')
      - name: Get version tags
        id: push-tag
        run: |
          TAGS=$(cat tags.txt)
          CSV_TAGS="${TAGS//$'\n'/,}"
          echo "names=${CSV_TAGS}" >> "${GITHUB_OUTPUT}"
      - name: Push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.push-tag.outputs.names }}
          build-args: |
            UBUNTU_VERSION=${{ steps.build-args.outputs.ubuntu_version }}
            CLANG_VERSION=${{ steps.build-args.outputs.clang_version }}
            IWYU_BRANCH=${{ steps.build-args.outputs.iwyu_baranch }}
      # - name: Push to version tag
      #   env:
      #     DOCKER_TAG: ${{ steps.build-args.outputs.ubuntu_version }}
      #     IMAGE_NAME: srzzumix/iwyu:local
      #     DOCKER_REPO: srzzumix/iwyu
      #   run: |
      #     ./hooks/post_push
