name: Docker Build
on:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        default: 'latest'
        description: 'ubuntu docker tag'
        required: true

jobs:
  trigger:
    run:
    strategy:
      include:
        - clang_version: 10
          iwyu_baranch: clagn_10
        - clang_version: 11
          iwyu_baranch: clagn_11
        - clang_version: 12
          iwyu_baranch: clagn_12
    steps:
      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker-build
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "ubuntu_version": "${{ github.event.inputs.ubuntu_version }}", "clang_version": "${{ matrix.clang_version }}", "iwyu_baranch": "${{ matrix.iwyu_baranch }}" }'
