name: Docker Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        default: 'latest'
        description: 'ubuntu docker tag'
        required: true
      clang_version:
        default: '13'
        description: 'clang version. see https://apt.llvm.org/'
        required: true
      iwyu_baranch:
        default: 'clang_13'
        description: 'include-what-you-use branch. see https://github.com/include-what-you-use/include-what-you-use/branches'
        required: true

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: srzzumix/iwyu:latest
          build-args: |
            UBUNTU_VERSION=${{ github.event.inputs.ubuntu_version || 'latest' }}
            CLANG_VERSION=${{ github.event.inputs.clang_version || '13' }}
            IWYU_VERSION=${{ github.event.inputs.iwyu_baranch || 'clang_13' }}
        if: (github.event_name != 'push' && github.ref != 'refs/heads/master')
      - name: Push to latest
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: srzzumix/iwyu:latest
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master')
      - name: Push to version tag
        env:
          DOCKER_TAG: latest
          IMAGE_NAME: srzzumix/iwyu:latest
          DOCKER_REPO: srzzumix/iwyu
        run: |
          ./hooks/post_push
