name: Docker Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        default: 'latest'
        description: 'clang version'
        required: true
      clang_version:
        default: ''
        description: 'clang version'
        required: true
      iwyu_baranch:
        default: ''
        description: 'include-what-you-use branch'
        required: true

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: srzzumix/iwyu:latest
      - name: Push to version tag
        env:
          DOCKER_TAG: latest
          IMAGE_NAME: srzzumix/iwyu:latest
          DOCKER_REPO: srzzumix/iwyu
        run: |
          ./hooks/post_push
